### ISSUE TITLE
please make sure version is consitent

### ISSUE THREAD

**Issue by mprins** [iobataya/dokuwiki-plugin-tabinclude#39]
Currently the version displayed on https://www.dokuwiki.org/plugin:tabinclude (2014-06-26) is ahead of that in https://github.com/iobataya/dokuwiki-plugin-tabinclude/blob/master/plugin.info.txt (2014-06-20) giving an update notification, but after updating the notification stays because the date in the wiki postdates that of the plugin code.

**Comment by iobataya** [comment]
Thank you for your notification. I'll check it right away.

**Comment by iobataya** [comment]
Now the dates of lastupdate in dokuwiki site and plugin.info.txt was corrected.

**Comment by mprins** [comment]
Thanx!
