### ISSUE TITLE
Incompatibility with Dokuwiki "Greebo"

### ISSUE THREAD

**Issue by ghost** [iobataya/dokuwiki-plugin-tabinclude#55]
I love this plugin but there seems to be some problems with the latest release of Dokuwiki "Greebo". 
It looks as if the pages render correctly but I get the following in my Apache error log:

`[Mon May 21 16:49:42.044688 2018] [proxy_fcgi:error] [pid 21522:tid 140024832714496] [client 10.20.50.33:65328] AH01071: Got error 'PHP message: PHP Warning:  Declaration of syntax_plugin_tabinclude_lines::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tabinclude/syntax/lines.php on line 44\nPHP message: PHP Warning:  Declaration of syntax_plugin_tabinclude_lines::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tabinclude/syntax/lines.php on line 44\nPHP message: PHP Warning:  Declaration of syntax_plugin_tabinclude_inline::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tabinclude/syntax/inline.php on line 42\nPHP message: PHP Warning:  Declaration of syntax_plugin_tabinclude_inline::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tabinclude/syntax/inline.php on line 42\nPHP message: PHP Warning:  Declaration of syntax_plugin_tabinclude_embed::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tabinclude/syntax/embed.php on line 40\nPHP message: PHP Warning:  Declaration of syntax_plugin_tabinclude_embed::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tabinclude/syntax/embed.php on line 40\nPHP message: PHP Warning:  Declaration of syntax_plugin_tabinclude_link::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tabinclude/syntax/link.php on line 40\nPHP message: PHP Warning:  Declaration of syntax_plugin_tabinclude_link::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tabinclude/syntax/link.php on line 40\nPHP message: PHP Warning:  Declaration of syntax_plugin_toggle::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /raid/wiki/htdocs/dokuwiki/lib/plugins/toggle/syntax.php on line 97\nPHP message: PHP Warning:  Declaration of syntax_plugin_toggle::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /raid/wiki/htdocs/dokuwiki/lib/plugins/toggle/syntax.php on line 97\nPHP message: PHP Warning:  Declaration of syntax_plugin_truetable::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /raid/wiki/htdocs/dokuwiki/lib/plugins/truetable/syntax.php on line 300\nPHP message: PHP Warning:  Declaration of syntax_plugin_truetable::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /raid/wiki/htdocs/dokuwiki/lib/plugins/truetable/syntax.php on line 300\nPHP message: PHP Warning:  Declaration of syntax_plugin_avtaskbox::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /raid/wiki/htdocs/dokuwiki/lib/plugins/avtaskbox/syntax.php on line 171\nPHP message: PHP Warning:  Declaration of syntax_plugin_avtaskbox::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /raid/wiki/htdocs/dokuwiki/lib/plugins/avtaskbox/syntax.php on line 171\nPHP message: PHP Warning:  Declaration of syntax_plugin_tablecalc::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tablecalc/syntax.php on line 86\nPHP message: PHP Warning:  Declaration of syntax_plugin_tablecalc::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /raid/wiki/htdocs/dokuwiki/lib/plugins/tablecalc/syntax.php on line 86\nPHP message: PHP Warning:  Declaration of syntax_plugin_cellbg::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /raid/wiki/htdocs/dokuwiki/lib/plugins/cellbg/syntax.php on line 123\nPHP message: PHP Warning:  Declaration of syntax_plugin_cellbg::render($mode, &$renderer, $data) should be compatible with DokuWiki_Syntax_Plugin::render($format, Doku_Renderer $renderer, $data) in /raid/wiki/htdocs/dokuwiki/lib/plugins/cellbg/syntax.php on line 123\n',`

Is there anything that can be done to improve compatibility?

**Comment by mprins** [comment]
php is complaining that the function signatures differ the `&$...` was removed in newer php (7+), it is not a greebo thing, but i think yu upgraded php as well or never looked at the warnings before..

the easy fix is to provide a pull request with update function signatures the old and new is in the warning message...

**Comment by iobataya** [comment]
I've fixed the function signatures. Now it looks woking good. Please update the plugin by Plugin Manager and check it in your environment.
